"""initial schema

Revision ID: 3fa99cd03408
Revises: 
Create Date: 2026-02-22 12:25:23.829458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fa99cd03408'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('has_standings', sa.Boolean(), nullable=False),
    sa.Column('has_statistics', sa.Boolean(), nullable=False),
    sa.Column('has_odds', sa.Boolean(), nullable=False),
    sa.Column('has_injuries', sa.Boolean(), nullable=False),
    sa.Column('has_predictions', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('games', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('num_games', sa.Integer(), nullable=False),
    sa.Column('combined_odds', sa.Float(), nullable=False),
    sa.Column('combined_probability', sa.Float(), nullable=False),
    sa.Column('kelly_stake', sa.Float(), nullable=False),
    sa.Column('target_odds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_accuracy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('total_predictions', sa.Integer(), nullable=False),
    sa.Column('correct_predictions', sa.Integer(), nullable=False),
    sa.Column('accuracy_pct', sa.Float(), nullable=False),
    sa.Column('avg_edge', sa.Float(), nullable=False),
    sa.Column('avg_confidence', sa.Integer(), nullable=False),
    sa.Column('total_staked', sa.Float(), nullable=False),
    sa.Column('total_returned', sa.Float(), nullable=False),
    sa.Column('profit_loss', sa.Float(), nullable=False),
    sa.Column('roi_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('venue_capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.String(length=50), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('referee', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('score_home_ht', sa.Integer(), nullable=True),
    sa.Column('score_away_ht', sa.Integer(), nullable=True),
    sa.Column('score_home_ft', sa.Integer(), nullable=True),
    sa.Column('score_away_ft', sa.Integer(), nullable=True),
    sa.Column('score_home_et', sa.Integer(), nullable=True),
    sa.Column('score_away_et', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_diff', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=10), nullable=True),
    sa.Column('home_played', sa.Integer(), nullable=False),
    sa.Column('home_won', sa.Integer(), nullable=False),
    sa.Column('home_drawn', sa.Integer(), nullable=False),
    sa.Column('home_lost', sa.Integer(), nullable=False),
    sa.Column('home_gf', sa.Integer(), nullable=False),
    sa.Column('home_ga', sa.Integer(), nullable=False),
    sa.Column('away_played', sa.Integer(), nullable=False),
    sa.Column('away_won', sa.Integer(), nullable=False),
    sa.Column('away_drawn', sa.Integer(), nullable=False),
    sa.Column('away_lost', sa.Integer(), nullable=False),
    sa.Column('away_gf', sa.Integer(), nullable=False),
    sa.Column('away_ga', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixture_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('shots_on_goal', sa.Integer(), nullable=True),
    sa.Column('shots_off_goal', sa.Integer(), nullable=True),
    sa.Column('total_shots', sa.Integer(), nullable=True),
    sa.Column('blocked_shots', sa.Integer(), nullable=True),
    sa.Column('shots_insidebox', sa.Integer(), nullable=True),
    sa.Column('shots_outsidebox', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('corner_kicks', sa.Integer(), nullable=True),
    sa.Column('offsides', sa.Integer(), nullable=True),
    sa.Column('ball_possession', sa.Float(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('goalkeeper_saves', sa.Integer(), nullable=True),
    sa.Column('total_passes', sa.Integer(), nullable=True),
    sa.Column('passes_accurate', sa.Integer(), nullable=True),
    sa.Column('passes_pct', sa.Float(), nullable=True),
    sa.Column('expected_goals', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('head_to_head',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team1_id', sa.Integer(), nullable=False),
    sa.Column('team2_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('score_home', sa.Integer(), nullable=False),
    sa.Column('score_away', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(length=10), nullable=True),
    sa.Column('total_goals', sa.Integer(), nullable=False),
    sa.Column('xg_home', sa.Float(), nullable=True),
    sa.Column('xg_away', sa.Float(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('injuries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('implied_probability', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_fixture_market', 'odds', ['fixture_id', 'market'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('selection', sa.String(length=50), nullable=False),
    sa.Column('poisson_probability', sa.Float(), nullable=False),
    sa.Column('ml_probability', sa.Float(), nullable=True),
    sa.Column('blended_probability', sa.Float(), nullable=False),
    sa.Column('best_odd', sa.Float(), nullable=False),
    sa.Column('best_bookmaker', sa.String(length=100), nullable=False),
    sa.Column('implied_probability', sa.Float(), nullable=False),
    sa.Column('edge', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('is_value_bet', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'market', 'selection', name='uq_fixture_market_selection')
    )
    op.create_table('team_last20',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=1), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('xg_for', sa.Float(), nullable=True),
    sa.Column('xg_against', sa.Float(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('shots_total', sa.Integer(), nullable=True),
    sa.Column('possession', sa.Float(), nullable=True),
    sa.Column('corners', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=1), nullable=False),
    sa.Column('form_weight', sa.Float(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['opponent_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'fixture_id', name='uq_team_fixture')
    )
    op.create_index('ix_team_last20_team_date', 'team_last20', ['team_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_last20_team_date', table_name='team_last20')
    op.drop_table('team_last20')
    op.drop_table('predictions')
    op.drop_index('ix_odds_fixture_market', table_name='odds')
    op.drop_table('odds')
    op.drop_table('injuries')
    op.drop_table('head_to_head')
    op.drop_table('fixture_statistics')
    op.drop_table('standings')
    op.drop_table('fixtures')
    op.drop_table('teams')
    op.drop_table('model_accuracy')
    op.drop_table('tickets')
    op.drop_table('leagues')
    # ### end Alembic commands ###
