"""add team_source_mappings

Revision ID: e2f4eca02e41
Revises: c3d4e5f6g7h8
Create Date: 2026-03-21 14:12:45.999740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e2f4eca02e41'
down_revision: Union[str, None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_source_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_football_team_id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('oddspapi_participant_id', sa.Integer(), nullable=True),
    sa.Column('oddspapi_name', sa.String(length=100), nullable=True),
    sa.Column('clubelo_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_source_mappings_api_football_team_id'), 'team_source_mappings', ['api_football_team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_source_mappings_api_football_team_id'), table_name='team_source_mappings')
    op.drop_table('team_source_mappings')
    # ### end Alembic commands ###
